import { useState, type FormEvent, type ReactNode } from "react";
import { Button } from "../../../shared/components/ui/button";
import { bankConnectionInputSchema } from "../schemas/bank-connections.schemas";
import type { BankConnection, BankConnectionInput } from "../types/bank-connections.types";

const inputClass = "h-10 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 text-sm text-slate-100 outline-none focus:border-indigo-500";
const defaults = { port:22, authenticationType:"PASSWORD" as const, inboundProcessedPath:"processed", inboundFailedPath:"failed", inboundSkippedPath:"skipped", inboundMaxFileSizeBytes:10485760, outboundMaxFileSizeBytes:10485760, connectTimeoutMs:10000, authenticationTimeoutMs:10000, operationTimeoutMs:30000 };

export function BankConnectionForm({ connection, pending, onSubmit, onCancel }: { connection?:BankConnection; pending:boolean; onSubmit:(input:BankConnectionInput)=>Promise<unknown>; onCancel?:()=>void }) {
  const profile=connection?.sftpProfile;
  const [values,setValues]=useState({
    code:connection?.code||"",bankName:connection?.bankName||"",displayName:connection?.displayName||"",
    host:profile?.host||"",port:profile?.port||defaults.port,username:profile?.username||"",authenticationType:profile?.authenticationType||defaults.authenticationType,
    credentialReference:"",knownHostsReference:"",inboundSourceName:profile?.inboundSourceName||"",
    inboundRemoteDirectory:profile?.inboundRemoteDirectory||"",inboundProcessedPath:profile?.inboundProcessedPath||defaults.inboundProcessedPath,
    inboundFailedPath:profile?.inboundFailedPath||defaults.inboundFailedPath,inboundSkippedPath:profile?.inboundSkippedPath||defaults.inboundSkippedPath,
    outboundRemoteDirectory:profile?.outboundRemoteDirectory||"",inboundMaxFileSizeBytes:profile?.inboundMaxFileSizeBytes||defaults.inboundMaxFileSizeBytes,
    outboundMaxFileSizeBytes:profile?.outboundMaxFileSizeBytes||defaults.outboundMaxFileSizeBytes,connectTimeoutMs:profile?.connectTimeoutMs||defaults.connectTimeoutMs,
    authenticationTimeoutMs:profile?.authenticationTimeoutMs||defaults.authenticationTimeoutMs,operationTimeoutMs:profile?.operationTimeoutMs||defaults.operationTimeoutMs,
  });
  const [error,setError]=useState<string|null>(null);
  async function submit(event:FormEvent){event.preventDefault();const candidate={code:values.code.trim().toUpperCase(),bankName:values.bankName,displayName:values.displayName,sftpProfile:{...values,credentialReference:values.credentialReference.trim()||undefined,knownHostsReference:values.knownHostsReference.trim()||undefined}};const parsed=bankConnectionInputSchema.safeParse(candidate);if(!parsed.success){setError(parsed.error.issues[0]?.message||"Review the configuration.");return;}if(!connection&&(!parsed.data.sftpProfile.credentialReference||!parsed.data.sftpProfile.knownHostsReference)){setError("Credential and known-hosts references are required when creating a connection.");return;}if(!window.confirm(connection?"Save these bank connection changes? Existing secret references remain unchanged when blank.":"Create this inactive bank connection?"))return;setError(null);try{await onSubmit(parsed.data);}finally{setValues(current=>({...current,credentialReference:"",knownHostsReference:""}));}}
  const set=(name:keyof typeof values,value:string|number)=>setValues(current=>({...current,[name]:value}));
  return <form onSubmit={submit} className="space-y-6">
    <fieldset disabled={pending}><legend className="text-base font-semibold text-white">Identity</legend><div className="mt-3 grid gap-4 md:grid-cols-3"><Field label="Code"><input className={inputClass} value={values.code} onChange={e=>set("code",e.target.value.toUpperCase())} required /></Field><Field label="Bank name"><input className={inputClass} value={values.bankName} onChange={e=>set("bankName",e.target.value)} required /></Field><Field label="Display name"><input className={inputClass} value={values.displayName} onChange={e=>set("displayName",e.target.value)} required /></Field></div></fieldset>
    <fieldset disabled={pending}><legend className="text-base font-semibold text-white">SFTP profile</legend><div className="mt-3 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
      <Field label="Host"><input className={inputClass} value={values.host} onChange={e=>set("host",e.target.value)} required /></Field><Field label="Port"><NumberInput value={values.port} onChange={v=>set("port",v)} /></Field><Field label="Username"><input className={inputClass} value={values.username} onChange={e=>set("username",e.target.value)} required /></Field><Field label="Authentication"><select className={inputClass} value={values.authenticationType} onChange={e=>set("authenticationType",e.target.value)}><option>PASSWORD</option><option>PRIVATE_KEY</option></select></Field>
      <Field label="Credential reference" hint={connection?"Leave blank to preserve the configured reference.":undefined}><input type="password" autoComplete="new-password" className={inputClass} value={values.credentialReference} onChange={e=>set("credentialReference",e.target.value)} required={!connection} /></Field><Field label="Known-hosts reference" hint={connection?"Leave blank to preserve the configured reference.":undefined}><input type="password" autoComplete="new-password" className={inputClass} value={values.knownHostsReference} onChange={e=>set("knownHostsReference",e.target.value)} required={!connection} /></Field>
      <Field label="Inbound source name"><input className={inputClass} value={values.inboundSourceName} onChange={e=>set("inboundSourceName",e.target.value)} required /></Field><Field label="Inbound remote directory"><input className={inputClass} value={values.inboundRemoteDirectory} onChange={e=>set("inboundRemoteDirectory",e.target.value)} placeholder="/inbound" required /></Field><Field label="Processed path"><input className={inputClass} value={values.inboundProcessedPath} onChange={e=>set("inboundProcessedPath",e.target.value)} required /></Field><Field label="Failed path"><input className={inputClass} value={values.inboundFailedPath} onChange={e=>set("inboundFailedPath",e.target.value)} required /></Field><Field label="Skipped path"><input className={inputClass} value={values.inboundSkippedPath} onChange={e=>set("inboundSkippedPath",e.target.value)} required /></Field><Field label="Outbound remote directory"><input className={inputClass} value={values.outboundRemoteDirectory} onChange={e=>set("outboundRemoteDirectory",e.target.value)} placeholder="/outbound" required /></Field>
      <Field label="Inbound max bytes"><NumberInput value={values.inboundMaxFileSizeBytes} onChange={v=>set("inboundMaxFileSizeBytes",v)} /></Field><Field label="Outbound max bytes"><NumberInput value={values.outboundMaxFileSizeBytes} onChange={v=>set("outboundMaxFileSizeBytes",v)} /></Field><Field label="Connect timeout ms"><NumberInput value={values.connectTimeoutMs} onChange={v=>set("connectTimeoutMs",v)} /></Field><Field label="Authentication timeout ms"><NumberInput value={values.authenticationTimeoutMs} onChange={v=>set("authenticationTimeoutMs",v)} /></Field><Field label="Operation timeout ms"><NumberInput value={values.operationTimeoutMs} onChange={v=>set("operationTimeoutMs",v)} /></Field>
    </div></fieldset>
    {error?<p className="text-sm text-rose-300" role="alert">{error}</p>:null}<div className="flex flex-wrap gap-3"><Button type="submit" disabled={pending}>{pending?"Saving...":"Save"}</Button>{onCancel?<Button type="button" variant="ghost" onClick={onCancel} disabled={pending}>Cancel</Button>:null}</div>
  </form>;
}
function Field({label,hint,children}:{label:string;hint?:string;children:ReactNode}){return <label className="space-y-2 text-sm font-medium text-slate-300"><span className="block">{label}</span>{children}{hint?<span className="block text-xs font-normal text-slate-500">{hint}</span>:null}</label>;}
function NumberInput({value,onChange}:{value:number;onChange:(value:number)=>void}){return <input type="number" className={inputClass} value={value} onChange={e=>onChange(Number(e.target.value))} required />;}
