import { useState, type ReactNode } from "react";
import { ArrowLeft, Power, PowerOff, RefreshCw, TestTube2 } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { ApiError } from "../../../core/http/api-error";
import { Button } from "../../../shared/components/ui/button";
import { Card } from "../../../shared/components/ui/card";
import { BankConnectionForm } from "../components/bank-connection-form";
import { useBankConnection, useConnectionHealth, useLifecycleBankConnection, useTestBankConnection, useUpdateBankConnection } from "../hooks/use-bank-connections";
import { bankConnectionIdSchema } from "../schemas/bank-connections.schemas";

export function BankConnectionDetailPage(){const id=useParams().bankConnectionId||"";const valid=bankConnectionIdSchema.safeParse(id).success;const detail=useBankConnection(id);const health=useConnectionHealth();const update=useUpdateBankConnection(id);const test=useTestBankConnection(id);const activate=useLifecycleBankConnection(id,"activate");const deactivate=useLifecycleBankConnection(id,"deactivate");const [editing,setEditing]=useState(false);const [notice,setNotice]=useState<string|null>(null);const [actionError,setActionError]=useState<string|null>(null);if(!valid)return <Shell><ErrorText text="Bank connection not found."/></Shell>;if(detail.isLoading)return <Shell><Card><p className="text-sm text-slate-400">Loading bank connection...</p></Card></Shell>;if(detail.error||!detail.data)return <Shell><Card><Error error={detail.error}/></Card></Shell>;const data=detail.data;const currentHealth=health.data?.connectionHealth.find(item=>item.ownership.bankConnectionId===id);const busy=update.isPending||test.isPending||activate.isPending||deactivate.isPending;
  function resetActionFeedback(){setNotice(null);setActionError(null);test.reset();activate.reset();deactivate.reset();}
  async function runTest(){if(!window.confirm("Run a non-destructive SFTP connectivity test now?"))return;resetActionFeedback();const result=await test.mutateAsync();if(result.outcome==="SUCCESS")setNotice(result.message);else setActionError(result.message||"SFTP connection test failed.");}
  async function lifecycle(action:"activate"|"deactivate"){if(!window.confirm(`${action==="activate"?"Activate":"Deactivate"} this bank connection?`))return;resetActionFeedback();await(action==="activate"?activate.mutateAsync():deactivate.mutateAsync());setNotice(`Bank connection ${action}d.`);}
  return <Shell><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold text-white">{data.displayName}</h1><p className="mt-2 text-sm text-slate-400">{data.code} · {data.bankName}</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" title="Refresh connection" onClick={()=>{void detail.refetch();void health.refetch();}} disabled={busy}><RefreshCw className="h-4 w-4"/></Button><Button variant="secondary" onClick={()=>void runTest()} disabled={busy}><TestTube2 className="mr-2 h-4 w-4"/>{test.isPending?"Testing...":"Test connection"}</Button>{data.status==="ACTIVE"?<Button variant="secondary" onClick={()=>void lifecycle("deactivate")} disabled={busy}><PowerOff className="mr-2 h-4 w-4"/>Deactivate</Button>:<Button onClick={()=>void lifecycle("activate")} disabled={busy}><Power className="mr-2 h-4 w-4"/>Activate</Button>}</div></div>
    {notice?<p className="mt-4 text-sm text-emerald-300" role="status">{notice}</p>:null}{actionError?<ErrorText text={actionError}/>:null}{[test.error,activate.error,deactivate.error].filter(Boolean).map((error,index)=><Error key={index} error={error as ApiError}/>)}
    <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric label="Administrative status" value={data.status}/><Metric label="Technical health" value={currentHealth?.technicalStatus||"Unavailable"}/><Metric label="Transport" value={data.sftpProfile?"SFTP":"Not configured"}/><Metric label="Updated" value={formatDate(data.updatedAt)}/></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><Card><h2 className="font-semibold text-white">Configuration</h2><Details rows={data.sftpProfile?[["Host",data.sftpProfile.host],["Port",String(data.sftpProfile.port)],["Username",data.sftpProfile.username],["Authentication",data.sftpProfile.authenticationType],["Credential",data.sftpProfile.credentialConfigured?"Configured":"Not configured"],["Known hosts",data.sftpProfile.knownHostsConfigured?"Configured":"Not configured"],["Inbound",data.sftpProfile.inboundRemoteDirectory],["Processed",data.sftpProfile.inboundProcessedPath],["Failed",data.sftpProfile.inboundFailedPath],["Skipped",data.sftpProfile.inboundSkippedPath],["Outbound",data.sftpProfile.outboundRemoteDirectory]]:[["Profile","Not configured"]]}/></Card><Card><h2 className="font-semibold text-white">Latest technical test</h2>{currentHealth?.latestTest?<Details rows={[["Outcome",currentHealth.latestTest.outcome],["Tested",formatDate(currentHealth.latestTest.occurredAt)],["Connection",currentHealth.latestTest.connectionEstablished?"Established":"Failed"],["Inbound",currentHealth.latestTest.inboundDirectoryAccessible?"Accessible":"Unavailable"],["Outbound",currentHealth.latestTest.outboundDirectoryAccessible?"Accessible":"Unavailable"],["Result",currentHealth.latestTest.message]]}/>:<p className="mt-4 text-sm text-slate-400">No technical test is available with the current permissions.</p>}<h3 className="mt-6 text-sm font-medium text-white">Timestamps</h3><Details rows={[["Created",formatDate(data.createdAt)],["Updated",formatDate(data.updatedAt)]]}/></Card></div>
    <Card className="mt-6"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold text-white">Edit connection</h2>{!editing?<Button variant="secondary" onClick={()=>setEditing(true)}>Edit</Button>:null}</div>{editing?<><BankConnectionForm connection={data} pending={update.isPending} onCancel={()=>setEditing(false)} onSubmit={async input=>{await update.mutateAsync(input);setEditing(false);setNotice("Bank connection saved. Existing secret references were not displayed.");}}/>{update.error?<Error error={update.error}/>:null}</>:<p className="text-sm text-slate-400">Secret references are write-only and are never preloaded into this form.</p>}</Card>
  </Shell>}
function Shell({children}:{children:ReactNode}){return <section><Link className="mb-5 inline-flex items-center gap-2 text-sm text-indigo-300 hover:underline" to="/bank-connections"><ArrowLeft className="h-4 w-4"/>Back to Bank Connections</Link>{children}</section>}
function Metric({label,value}:{label:string;value:string}){return <div className="border-l-2 border-slate-700 bg-slate-900/40 px-4 py-3"><p className="text-xs uppercase text-slate-500">{label}</p><p className="mt-2 break-words font-semibold text-white">{value}</p></div>}
function Details({rows}:{rows:string[][]}){return <dl className="mt-4 grid gap-3 sm:grid-cols-2">{rows.map(([label,value])=><div key={label}><dt className="text-xs uppercase text-slate-500">{label}</dt><dd className="mt-1 break-words text-sm text-slate-200">{value}</dd></div>)}</dl>}
function Error({error}:{error:Error|null}){return <ErrorText text={error instanceof ApiError&&error.status===403?"You do not have permission to perform this action.":error?.message||"The operation could not be completed."}/>}
function ErrorText({text}:{text:string}){return <p className="mt-4 text-sm text-rose-300" role="alert">{text}</p>}
function formatDate(value:string){return new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
