import { useState } from "react";
import { ExternalLink, Plus, RefreshCw } from "lucide-react";
import { Link } from "react-router-dom";
import { ApiError } from "../../../core/http/api-error";
import { PageHeader } from "../../../shared/components/page-header";
import { Button } from "../../../shared/components/ui/button";
import { Card } from "../../../shared/components/ui/card";
import { BankConnectionForm } from "../components/bank-connection-form";
import { useBankConnections, useConnectionHealth, useCreateBankConnection } from "../hooks/use-bank-connections";

export function BankConnectionsPage(){const [creating,setCreating]=useState(false);const [notice,setNotice]=useState<string|null>(null);const list=useBankConnections();const health=useConnectionHealth();const create=useCreateBankConnection();const healthById=new Map(health.data?.connectionHealth.map(item=>[item.ownership.bankConnectionId,item]));return <section>
  <div className="flex items-start justify-between gap-4"><PageHeader title="Bank Connections" description="Configure and monitor organization-scoped SFTP bank connections."/><div className="flex gap-2"><Button variant="secondary" title="Refresh connections" onClick={()=>{void list.refetch();void health.refetch();}} disabled={list.isFetching}><RefreshCw className={`h-4 w-4 ${list.isFetching?"animate-spin":""}`}/></Button><Button onClick={()=>setCreating(true)} disabled={creating}><Plus className="mr-2 h-4 w-4"/>New connection</Button></div></div>
  {creating?<Card className="mb-5"><BankConnectionForm pending={create.isPending} onCancel={()=>setCreating(false)} onSubmit={async input=>{await create.mutateAsync(input);setCreating(false);setNotice("Bank connection created as inactive.");}}/>{create.error?<ErrorText error={create.error}/>:null}</Card>:null}
  {notice?<p className="mb-4 text-sm text-emerald-300" role="status">{notice}</p>:null}
  {list.isLoading?<Card><p className="text-sm text-slate-400">Loading bank connections...</p></Card>:null}
  {list.error?<Card><ErrorText error={list.error}/><Button className="mt-4" variant="secondary" onClick={()=>void list.refetch()}>Retry</Button></Card>:null}
  {list.data?.length===0?<Card><h2 className="font-medium text-white">No bank connections configured</h2><p className="mt-2 text-sm text-slate-400">Create an inactive connection, test it, then activate it.</p></Card>:null}
  {list.data&&list.data.length>0?<div className="overflow-x-auto border-y border-slate-800 bg-slate-900/40"><table className="min-w-[1150px] text-left text-sm"><caption className="sr-only">Bank connections visible to the current organization</caption><thead className="bg-slate-950 text-slate-400"><tr>{["Connection","Code","Bank","Status","Health","Transport","Inbound","Outbound","Updated",""].map((h,i)=><th key={`${h}-${i}`} className="px-4 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{list.data.map(item=>{const technical=healthById.get(item.bankConnectionId);const profile=item.sftpProfile;return <tr key={item.bankConnectionId} className="border-t border-slate-800 text-slate-200"><td className="px-4 py-4"><Link className="font-medium text-indigo-300 hover:underline" to={`/bank-connections/${item.bankConnectionId}`}>{item.displayName}</Link></td><td className="px-4 py-4 font-mono text-xs">{item.code}</td><td className="px-4 py-4">{item.bankName}</td><td className="px-4 py-4"><Badge value={item.status}/></td><td className="px-4 py-4"><Badge value={technical?.technicalStatus||"UNAVAILABLE"}/></td><td className="px-4 py-4">{profile?"SFTP":"Not configured"}</td><td className="px-4 py-4">{profile?.inboundRemoteDirectory?"Enabled":"Not configured"}</td><td className="px-4 py-4">{profile?.outboundRemoteDirectory?"Enabled":"Not configured"}</td><td className="whitespace-nowrap px-4 py-4">{formatDate(item.updatedAt)}</td><td className="px-4 py-4"><Link aria-label={`View ${item.displayName}`} className="text-indigo-300" to={`/bank-connections/${item.bankConnectionId}`}><ExternalLink className="h-4 w-4"/></Link></td></tr>;})}</tbody></table></div>:null}
</section>}
function Badge({value}:{value:string}){const good=value==="ACTIVE"||value==="HEALTHY";return <span className={`inline-flex rounded-full border px-2 py-1 text-xs ${good?"border-emerald-500/30 bg-emerald-500/10 text-emerald-300":"border-slate-700 bg-slate-800 text-slate-300"}`}>{value}</span>}
function ErrorText({error}:{error:Error}){return <p className="mt-3 text-sm text-rose-300" role="alert">{error instanceof ApiError&&error.status===403?"You do not have permission to manage bank connections.":error.message}</p>}
function formatDate(value:string){return new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
